---

- name: Install node package manager
  homebrew: "name=npm state=present"
  when: global_google_fonts or group_google_fonts or personal_google_fonts

- name: Install Google Fonts Installer
  shell: npm install -g google-font-installer
  when: global_google_fonts or group_google_fonts or personal_google_fonts

- name: Install global Google Fonts.
  shell: gfi install "{{ item }}"
  with_items: "{{ global_google_fonts }}"
  when: global_google_fonts

- name: Install group Google Fonts.
  shell: gfi install "{{ item }}"
  with_items: "{{ global_google_fonts }}"
  when: group_google_fonts

- name: Install personal Google Fonts.
  shell: gfi install "{{ item }}"
  with_items: "{{ global_google_fonts }}"
  when: personal_google_fonts
